main:
    # name: my_name # name is set to name of config file per default
    data_path: '../data'
    log_path: '../logs'
    log_level: INFO # log_level for log files

neptune:
    activate: true  # set to false to completely deactivate Neptune
    init:
        project_qualified_name: florian.wilhelm/lda4rec  # `shared/onboarding` if no account
        api_token: '~/.neptune_api_token' # `ANONYMOUS` if no account
    create_experiment:
        name: lda4rec-v1

experiment:
    dataset: movielens-100k
    dataset_seed: 1729
    interaction_pivot: 4
    model_seed: 123
    max_user_interactions: 200
#    estimator: BilinearBPREst
#    est_params:
#        embedding_dim: 8
#        sparse: False
#        n_iter: 20
#        learning_rate: 0.01
    estimator: LDA4RecEst
    est_params:
        embedding_dim: 4
        n_iter: 1000
        batch_size: 128
        learning_rate: 0.01
