main:
    # name: my_name # name is set to name of config file per default
    data_path: '../data'
    log_path: '../logs'
    log_level: INFO # log_level for log files

neptune:
    project: florian.wilhelm/lda4rec-movielens1m  # `shared/onboarding` if no account
    api_token: '~/.neptune_api_token' # `ANONYMOUS` if no account
    tags: ["movielens-1m", "exp_run1"]
    description: "Experiment run on GCP"
    mode: "async" # or "offline", "sync", "debug"

experiment:
    dataset: movielens-1m
    dataset_seed: 1729
    interaction_pivot: 4
    model_seed: 123
    max_user_interactions: -1
    estimator: MFEst
    est_params:
        embedding_dim: 4
        n_iter: 10
        batch_size: 128
        learning_rate: 0.01
