main:
    # name: my_name # name is set to name of config file per default
    data_path: '../data'
    log_path: '../logs'
    log_level: INFO # log_level for log files

neptune:
    project: neptune.user/lda4rec-exp  # `shared/onboarding` if no account
    api_token: '~/.neptune_api_token' # `ANONYMOUS` if no account
    tags: ["lda-cmp"]
    description: "Experiment run on GCP"
    mode: "async" # or "offline", "sync", "debug"

experiment:
    dataset: movielens-100k
    dataset_seed: 1729
    interaction_pivot: 0
    model_seed: 3128845410
    max_user_interactions: 200
    estimator: LDA4RecEst
    est_params:
        embedding_dim: 16
        n_iter: 10000
        batch_size: 128
        learning_rate: 0.001
